[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "either"
allow = [
    "Apache-2.0",
    "MIT",
    "Unlicense",
]

[bans]
multiple-versions = "deny"
skip = [
    { name = "hashbrown", version = "0.9.1" }
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
ignore = [
]

[sources]
unknown-registry = "deny"
unknown-git = "allow"